### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Biggitybaked** [razewerz/Instagram-accounts-creator#2]
-firefox
Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/fake_useragent/utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range
Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.2117.157 Safari/537.36
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/data/data/com.termux/files/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/data/data/com.termux/files/usr/lib/python3.10/subprocess.py", line 1840, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'your gecko driver here'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Instagram-accounts-creator/botAccountCreate.py", line 26, in <module>
    driver = webdriver.Firefox(firefox_profile=profile, executable_path=r"your gecko driver here")
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'your gecko driver here' executable needs to be in PATH.

**Comment by Ctrl-Z-dev** [comment]
did you find a way to solve it i am new to python and half of the code i am reading is new to me, so any help would be appreciated 
@Biggitybaked

**Comment by razewerz** [comment]
I think you are using the code on the phone, so selenium automation cannot work for it.

**Comment by Ctrl-Z-dev** [comment]
no not really is it working on your end?

**Comment by Ctrl-Z-dev** [comment]
No not really, I am using a laptop, what can the probleme be

**Comment by Ctrl-Z-dev** [comment]
https://www.codenong.com/cs105354439/
i think this could help, btw i am new to the whole programing process and
just wanted to know how to automate

**Comment by razewerz** [comment]
Then. You just need your executable browser driver and link it the path on
the source code on “botAccountCreate.py” , where i commented “your gecko
driver here” in case you are using firefox , or chrome with chromedriver ,
just do some search on google you ll find them.

**Comment by Ctrl-Z-dev** [comment]
Awesome, thanks!
